###########################################################################
#    .
#   /|\
#  / |/\
# | \|.|
# \.|/ /
#  \|/
#   `|´
#    |
# This file was written by Steve "Grasseh" Gagné and can be reused for free.
# It contains aliases, functions and variables meant to be used on a nu shell
############################################################################
startup = [
  "source ~/.config/nu/git_functions.nu",
  "source ~/.config/nu/metrio_functions.nu",
#---------------------------------------------------------------------
# Aliases
# ---------------------------------------------------------------------
  "alias la = ls --long",
#---------------------------------------------------------------------
# Git aliases
# ---------------------------------------------------------------------
# general
  "alias gs = git status",
  "alias gf = git fetch",
  "alias gr = git rebase",
  "alias gra = git rebase --abort",
  "alias grc = git rebase --continue",
  "alias grh = git reset --hard",
  "alias ggc = git gc",
# add
  "alias ga = git add",
  "alias gaa = git add -A .",
# commit
  "alias gcm = git commit -m",
  "alias gca = git commit --amend",
# merge
  "alias gcp = git cherry-pick",
  "alias gm = git merge --no-ff",
# log
  "alias gl = git log --graph --abbrev-commit --decorate --date=relative --format=format:'%C(bold cyan)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(magenta)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all",
  "alias gl2 = git log --graph --abbrev-commit --decorate --format=format:'%C(bold cyan)%h%C(reset) - %C(bold green)%aD%C(reset) %C(dim green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n          %C(white)%s%C(reset) %C(magenta)- %an%C(reset)' --all",
  "alias glw = gl --since \"1 week ago\" --author \"Steve Gagné\"",
  "alias grl = git reflog",
# push
  "alias gp = git push",
  "alias gpom = git push origin master",
  "alias gpu = git push -u",
  "alias gpf = git push -f",
  "alias gpuo = git push -u origin",
  "alias gplm = git push live master",
# branch
  "alias gch = git checkout",
  "alias gchb = git checkout -b",
  "alias gchp = git checkout production",
  "alias gb = git branch",
  "alias gba = git branch -a",
  "alias gbd = git branch -d",
  "alias gbD = git branch -D",
  "alias gbod = git push origin --delete",
# stash
  "alias gsh = git stash",
  "alias gshp = git stash pop",
# tags
  "alias gpt = git push origin --tags",
  "alias gt = git tag",
  "alias gts = git tag show",
  "alias gta = git tag -a",
  "alias gtd = git tag -d",
  "alias gtl = git tag -l",
# diff
  "alias gd = git diff",
  "alias gdw = git diff -w",
  "alias gdc = git diff --cached",
#bisect
  "alias gbi = git bisect",
  "alias gbis = git bisect start",
  "alias gbib = git bisect bad",
  "alias gbig = git bisect good",
  "alias gbir = git bisect reset",
#Remote
  "alias gre = git remote",
  "alias grea = git remote add",
  "alias gres = git remote set-url",
  "alias greso = git remote set-url origin",
  "alias grer = git remote remove",
# ---------------------------------------------------------------------
# Directory aliases
# ---------------------------------------------------------------------
  "alias desktop = cd ~/Desktop",
  "alias dotfiles = cd ~/dotfiles",
  "alias grasseh = cd ~/projects/grasseh.com",
  "alias home = cd ~",
  "alias projects = cd ~/projects/",
  "alias m1 = cd ~/projects/metrio/backend",
  "alias m2 = cd ~/projects/metrio2/backend",
  "alias m3 = cd ~/projects/metrio3/backend",
  "alias m4 = cd ~/projects/metrio4/backend",
  "alias m5 = cd ~/projects/metrio5/backend",
  "alias m1d = cd ~/projects/metrio/devops",
  "alias m2d = cd ~/projects/metrio2/devops",
  "alias m3d = cd ~/projects/metrio3/devops",
  "alias m4d = cd ~/projects/metrio4/devops",
  "alias m5d = cd ~/projects/metrio5/devops",
  "alias lm = ~/metrio.sh",
# ---------------------------------------------------------------------
# Other aliases
# ---------------------------------------------------------------------
  "alias ~ = cd ~",
  "alias aliases = vim ~/dotfiles/links/.bash_profile",
  "alias bigfiles = sudo find / -xdev -type f -size +200M -exec du -bh {}",
  "alias brails = bin/rails",
  "alias bril = xrandr --output eDP-1 --brightness",
  "alias brih = xrandr --output HDMI-1 --brightness",
  "alias c = clear",
  "alias ccip = circleci config process .circleci/config.yml > process.yml",
  "alias ccie = circleci local execute -c process.yml --job",
  "alias deploy = ssh-add && ssh -A root@devops.metrio.net",
  "alias dc = docker-compose",
  "alias dcu = docker-compose up",
  "alias fiap = frontend_is_always_problems",
  "alias gitgud = echo '[ ] not rekt  [x] rekt'",
  "alias la = ls -alsh",
  "alias mdbr = sudo service mongod restart",
  "alias notes = vim ~/notes.MD",
  "alias path = echo -e ${PATH//:/\\n}",
  "alias rdw = bin/rails dev:watch",
  "alias rdwf = bin/rails dev:watch_full",
  "alias reload = config load ~/.config/nu/config.toml",
  "alias rmr = sudo rm -R",
  "alias rms = find . -name '*.swp' -exec rm -i '{}'",
  "alias ssa = ssh-add ~/.ssh/id_rsa",
  "alias todo = vim ~/todo.MD",
  "alias v = vim"
]

# ---------------------------------------------------------------------
# Other options
# ---------------------------------------------------------------------
use_italics = true
tab_width = 2
